litellm_settings:
  drop_params: true
model_list:
  - model_name: claude-sonnet-4-6
    litellm_params:
      model: ollama/gpt-oss:120b-cloud
  - model_name: claude-3-7-sonnet-20250219
    litellm_params:
      model: ollama/gpt-oss:120b-cloud
  - model_name: claude-3-7-sonnet
    litellm_params:
      model: ollama/gpt-oss:120b-cloud
  - model_name: claude-3-5-sonnet-20241022
    litellm_params:
      model: ollama/gpt-oss:20b
  - model_name: claude-3-5-haiku-20241022
    litellm_params:
      model: ollama/qwen3:1.7b
  - model_name: phi4-mini
    litellm_params:
      model: ollama/phi4-mini
  - model_name: qwen3-small
    litellm_params:
      model: ollama/qwen3:1.7b
